name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check HTML file
        run: test -f index.html

      - name: Check CSS file
        run: test -f style.css

      - name: Check JavaScript file
        run: test -f script.js
